services:

  server:
    build: .
    container_name: server
    restart: always
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOSTS}
      - LETSENCRYPT_HOST=${ALLOWED_HOSTS}
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    command: >
      bash -c "cd app && 
               poetry run python manage.py collectstatic --noinput && 
               poetry run python manage.py migrate && 
               cd .. && 
               poetry run gunicorn -b 0.0.0.0:8000 --chdir app app.wsgi:application"


volumes:
  static_volume:
  media_volume: