version: '3'

services:
  app:
    build: .
    container_name: sinevo_mem
    restart: always
    networks:
      - proxy-net
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=xn--b1alpfl2h.xn--p1ai
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=xn--b1alpfl2h.xn--p1ai
      - LETSENCRYPT_EMAIL=vv1zard3x@ya.ru
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ENABLE_IPV6=true
      - HTTPS_METHOD=redirect
      - SSL_POLICY=Mozilla-Modern
      - DEBUG=true
    command:
      - ./main

networks:
  proxy-net:
    external: true 