version: '3'

services:
  app:
    build: .
    container_name: sinevo_mem
    restart: always
    networks:
      - proxy-net
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=синёво.рф
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=синёво.рф
      - LETSENCRYPT_EMAIL=vv1zard3x@ya.ru
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEBUG=true
    command:
      - ./main

networks:
  proxy-net:
    external: true 